services:
  microservice:
    image: ghcr.io/bozonx/grand-publicador:latest
    container_name: grand-publicador
    hostname: grand-publicador
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - LOG_LEVEL=warn
      - JWT_SECRET=slkdf923598ksfdo7853kjlksdfu4oi5jkssf908kj
      - TELEGRAM_BOT_TOKEN=your_token_here
      - API_KEY=your_api_key_here
    volumes:
      - ./data:/data
      - ./app-config.yaml:/data/app-config.yaml
    healthcheck:
      test: [ 'CMD-SHELL', 'wget -qO- http://127.0.0.1:8080/api/v1/health || exit 1' ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
